### PR TITLE
AndroidX migration and upgraded PaperDB and RxJava2 versions

### PR DESCRIPTION
**Pull request by kishandonga**
- AndroidX migration
- Android 10 Supported
- Paper DB new version supported 2.7.1
- RxJava new version supported 2.2.10
- Junit testing new version supported 4.13
- Gradle migration 3.0.1 to 3.6.3
- Document updated as per open issue for the document
- RxPaperBook make variable private
- Manifest orientation issue ignored

### CODE REVIEW

**Comment by pakoito** [comment]
Thank you for the PR, good changes. I would rather keep the fields with the encapsulation they have how, if you don't mind reverting that one change.

I'll merge and release a new version afterwards :D

**Comment by kishandonga** [comment]
Sure not an issue thank you for your quick response

**Comment by kishandonga** [comment]
please merged it so every one get latest code and new version

**Comment by pakoito** [comment]
Please, just a small change to revert these lines to their original encapsulation:

https://i.imgur.com/2HHcOPL.png

**Comment by kishandonga** [comment]
Okay as suggested code committed.

**Comment by pakoito** [comment]
Thank you, let's ship!

**Pull request merged**
